[package]
name = "todo-cli"
version = "1.0.0"
edition = "2024"
description="A simple todo CLI app in Rust."
license="MIT"

[dependencies]
anyhow = "1.0.98"
clap = {version="4.5.39", features = ["derive"]}
inquire = "0.7.5"
serde = {version="1.0.219", features = ["derive"]}
serde_json = "1.0.140"
